customhost = "employee.cvyrc56fzszp.ap-southeast-1.rds.amazonaws.com"
customuser = "rajendra"
custompass = "rajendra123"
customdb = "employee"
custombucket = "aws-project-employee"
customregion = "ap-southeast-1"
